From php:5.6-apache

RUN apt-get update

COPY public-html/ /var/www/html/

#FROM httpd:2.4
#
#COPY files/my-httpd.conf /usr/local/apache2/conf/httpd.conf
#COPY files/my-httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
#COPY public-html /usr/local/apache2/htdocs/